# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.13-slim
WORKDIR /app
COPY . .
RUN pip install mcp google-auth google-auth-oauthlib google-api-python-client fastmcp
CMD ["python", "server.py"]
